### ISSUE TITLE
ESM files don't show up in the mod list

### ISSUE THREAD

**Issue by actuallyallama** [FlakTheMighty/Fallout-4-Config-Tool#1]
It's possible to unload fallout 4's esm file, and then you have to manually edit the plugins file to get it back - also, I can't use the tool to load esm based mods such as Homemaker.

**Comment by FlakTheMighty** [comment]
The way the plugins list works, there isn't a Fallout4.esm, but adding other ones should be easy enough - just have to add an extra check for .esm in addition to .esp

**Comment by FlakTheMighty** [comment]
(done)[http://i.imgur.com/YHFWonj.png]
It's done, I'll be pushing the new version soon.

**Comment by FlakTheMighty** [comment]
Actually it appears that Fallout4.esm is added into the list by the launcher itself now, I'll revert the change to remove it from the list and keep it at index 0 either today or tomorrow.
